### ISSUE TITLE
Denoising Autoencoders

### ISSUE THREAD

**Issue by Mmiglio** [Mmiglio/SpeechRecognition#6]
We can use denoising autoencoders to learn robust features. 

First test seems to be working: 

![denoising](https://user-images.githubusercontent.com/26923771/60834242-85143e80-a1c0-11e9-9459-6af3c509255e.png)

**Comment by mac40** [comment]
# documentation for autoencoders
* [Build the right Autoencoder part 1](https://towardsdatascience.com/build-the-right-autoencoder-tune-and-optimize-using-pca-principles-part-i-1f01f821999b)
* [Build the right Autoencoder part 2](https://towardsdatascience.com/build-the-right-autoencoder-tune-and-optimize-using-pca-principles-part-ii-24b9cca69bd6)
